jobs:
  test:
    runs-on: [ubuntu-latest,macos-latest,windows-latest]
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.x', '2.x']
    steps:
    - uses: actions/checkout@v2
    - name: Install python ${{ matrix.python-version }}
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
    - run: |
        pip install -r requirements.txt
    - name: Run tests
    - run: |
        pytest